// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfYdlfeh48vK2kl9pOAD5JdldEgtd_sOc',
    appId: '1:345113232057:web:d2e75860bed3badb645168',
    messagingSenderId: '345113232057',
    projectId: 'my-insta-bb04b',
    authDomain: 'my-insta-bb04b.firebaseapp.com',
    storageBucket: 'my-insta-bb04b.appspot.com',
    measurementId: 'G-V5M7ESNNEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsDKi9SXIisnp-0mRbLuQQLBHlQHNnZ1g',
    appId: '1:345113232057:android:51c2ce3f803f1e01645168',
    messagingSenderId: '345113232057',
    projectId: 'my-insta-bb04b',
    storageBucket: 'my-insta-bb04b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM6R8Y5Nk7NMj3tsRTcxLXwjRg-wh4D68',
    appId: '1:345113232057:ios:1d4f605103e0f3de645168',
    messagingSenderId: '345113232057',
    projectId: 'my-insta-bb04b',
    storageBucket: 'my-insta-bb04b.appspot.com',
    iosBundleId: 'com.example.nikeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM6R8Y5Nk7NMj3tsRTcxLXwjRg-wh4D68',
    appId: '1:345113232057:ios:1d4f605103e0f3de645168',
    messagingSenderId: '345113232057',
    projectId: 'my-insta-bb04b',
    storageBucket: 'my-insta-bb04b.appspot.com',
    iosBundleId: 'com.example.nikeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3yE5uHcINNbvDiYtApytNjYmVgOo6iIY',
    appId: '1:345113232057:web:7dc055ab25b6841c645168',
    messagingSenderId: '345113232057',
    projectId: 'my-insta-bb04b',
    authDomain: 'my-insta-bb04b.firebaseapp.com',
    storageBucket: 'my-insta-bb04b.appspot.com',
    measurementId: 'G-LYKCSSL8HW',
  );
}
